// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrbxrmnvcwdvtnexcpjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYnhybW52Y3dkdnRuZXhjcGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDc1OTIsImV4cCI6MjA2NTEyMzU5Mn0.-FeCKWSPbaEfSBqp4jyu2190cxd_ZslXJSdxDbm2Ns8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);